FROM golang:1.16-alpine

EXPOSE 8080

WORKDIR /go/src/app
COPY . .

ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost
ENV REDIS_HOST=redis
ENV POSTGRES_HOST=postgres
ENV POSTGRES_USER=example
ENV POSTGRES_PASSWORD=example
ENV POSTGRES_DATABASE=test

RUN go build && \
    addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser
CMD ["./server"]